# Generated by Django 6.0.5 on 2026-06-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='performance_score',
            field=models.FloatField(default=5.0),
        ),
    ]
